### ISSUE TITLE
django should wait for postgres to start up

### ISSUE THREAD

**Issue by pbinkley** [DocNow/docnow#1]
```docker-compose up``` throws a lot of errors, and ends up not serving. It appears that the db server failed to start.

docker-compose 1.8.1 on Ubuntu 16.04

```
...
webpack_1  | npm info lifecycle docnow@0.0.1~postclean: docnow@0.0.1
webpack_1  | npm info ok 
webpack_1  | Project is running at http://0.0.0.0:3000/
webpack_1  | webpack output is served from http://0.0.0.0:3000/assets/bundles/
webpack_1  | (node:38) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
webpack_1  | parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
db_1       | creating configuration files ... ok
django_1   | Traceback (most recent call last):
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
django_1   |     self.connect()
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 171, in connect
django_1   |     self.connection = self.get_new_connection(conn_params)
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
django_1   |     connection = Database.connect(**conn_params)
django_1   |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
django_1   |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django_1   | psycopg2.OperationalError: could not connect to server: Connection refused
django_1   | 	Is the server running on host "db" (172.18.0.5) and accepting
django_1   | 	TCP/IP connections on port 5432?
django_1   | 
django_1   | 
django_1   | The above exception was the direct cause of the following exception:
django_1   | 
django_1   | Traceback (most recent call last):
django_1   |   File "/usr/local/bin/django-admin", line 11, in <module>
django_1   |     sys.exit(execute_from_command_line())
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
django_1   |     utility.execute()
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
django_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
django_1   |     self.execute(*args, **cmd_options)
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
django_1   |     output = self.handle(*args, **options)
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 83, in handle
django_1   |     executor = MigrationExecutor(connection, self.migration_progress_callback)
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 20, in __init__
django_1   |     self.loader = MigrationLoader(self.connection)
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 52, in __init__
django_1   |     self.build_graph()
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 203, in build_graph
django_1   |     self.applied_migrations = recorder.applied_migrations()
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
django_1   |     self.ensure_schema()
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
django_1   |     if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 231, in cursor
django_1   |     cursor = self.make_debug_cursor(self._cursor())
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 204, in _cursor
django_1   |     self.ensure_connection()
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
django_1   |     self.connect()
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
django_1   |     six.reraise(dj_exc_type, dj_exc_value, traceback)
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
django_1   |     raise value.with_traceback(tb)
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
django_1   |     self.connect()
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 171, in connect
django_1   |     self.connection = self.get_new_connection(conn_params)
django_1   |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
django_1   |     connection = Database.connect(**conn_params)
django_1   |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
django_1   |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django_1   | django.db.utils.OperationalError: could not connect to server: Connection refused
django_1   | 	Is the server running on host "db" (172.18.0.5) and accepting
django_1   | 	TCP/IP connections on port 5432?
django_1   | 
db_1       | running bootstrap script ... ok
db_1       | performing post-bootstrap initialization ... ok
trends_1   | ERROR:root:could not connect to server: Connection refused
trends_1   | 	Is the server running on host "db" (172.18.0.5) and accepting
trends_1   | 	TCP/IP connections on port 5432?
trends_1   | 
db_1       | syncing data to disk ... ok
db_1       | 
db_1       | Success. You can now start the database server using:
db_1       | 
db_1       |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1       | 
db_1       | 
db_1       | WARNING: enabling "trust" authentication for local connections
db_1       | You can change this by editing pg_hba.conf or using the option -A, or
db_1       | --auth-local and --auth-host, the next time you run initdb.
db_1       | ****************************************************
db_1       | WARNING: No password has been set for the database.
db_1       |          This will allow anyone with access to the
db_1       |          Postgres port to access your database. In
db_1       |          Docker's default configuration, this is
db_1       |          effectively any other container on the same
db_1       |          system.
db_1       | 
db_1       |          Use "-e POSTGRES_PASSWORD=password" to set
db_1       |          it in "docker run".
db_1       | ****************************************************
db_1       | waiting for server to start....LOG:  database system was shut down at 2017-03-24 18:16:36 UTC
db_1       | LOG:  MultiXact member wraparound protections are now enabled
db_1       | LOG:  database system is ready to accept connections
db_1       | LOG:  autovacuum launcher started
db_1       |  done
db_1       | server started
db_1       | ALTER ROLE
db_1       | 
db_1       | 
db_1       | /docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1       | 
db_1       | LOG:  received fast shutdown request
db_1       | LOG:  aborting any active transactions
db_1       | waiting for server to shut down...LOG:  autovacuum launcher shutting down
db_1       | .LOG:  shutting down
db_1       | LOG:  database system is shut down
db_1       |  done
db_1       | server stopped
db_1       | 
db_1       | PostgreSQL init process complete; ready for start up.
db_1       | 
db_1       | LOG:  database system was shut down at 2017-03-24 18:16:43 UTC
db_1       | LOG:  MultiXact member wraparound protections are now enabled
db_1       | LOG:  database system is ready to accept connections
db_1       | LOG:  autovacuum launcher started
db_1       | ERROR:  relation "docnow_user" does not exist at character 302
db_1       | STATEMENT:  SELECT "docnow_user"."id", "docnow_user"."password", "docnow_user"."last_login", "docnow_user"."is_superuser", "docnow_user"."username", "docnow_user"."first_name", "docnow_user"."last_name", "docnow_user"."email", "docnow_user"."is_staff", "docnow_user"."is_active", "docnow_user"."date_joined" FROM "docnow_user" WHERE "docnow_user"."is_superuser" = true
trends_1   | ERROR:root:relation "docnow_user" does not exist
trends_1   | LINE 1: ...er"."is_active", "docnow_user"."date_joined" FROM "docnow_us...
trends_1   |                                                              ^
trends_1   | 
```

(the "relation docnow_user does not exist" error repeats many many times)

**Comment by edsu** [comment]
Interesting! It looks like a timing issue -- docker-compose [expresses the dependency] that the django has on the db, but I think the container could be running without the db being fully up. I'm curious though, is the app running ok on http:/localhost:8000/ or did the django container quit? You can see if you do a:

    docker ps -a

**Comment by pbinkley** [comment]
I get this list:

```
CONTAINER ID        IMAGE                COMMAND                  CREATED              STATUS              PORTS                    NAMES
c9357c0d7b7d        docnow_trends        "/bin/bash -c 'sle..."   About a minute ago   Up About a minute                            docnow_trends_1
25f4ec315712        docnow_django        "/bin/bash -c 'sle..."   About a minute ago   Up About a minute   0.0.0.0:8000->8000/tcp   docnow_django_1
36f7bbe006e3        postgres             "docker-entrypoint..."   About a minute ago   Up About a minute   5432/tcp                 docnow_db_1
dcb21e9cd135        docnow_webpack       "npm run start"          About a minute ago   Up About a minute   0.0.0.0:3000->3000/tcp   docnow_webpack_1
a708b7a58dc3        redis                "docker-entrypoint..."   About a minute ago   Up About a minute   6379/tcp                 docnow_redis_1
5d18d6b298b2        catatnight/postfix   "/bin/sh -c '/opt/..."   About a minute ago   Up About a minute                            docnow_mail_1
```

I had already shut it down, so I deleted all the containers and images and restarted from scratch. This time the http server is responding at localhost:8000, and I get this error:

```
ProgrammingError at /

relation "docnow_user" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "docnow_user"
                                          ^

Request Method: 	GET
Request URL: 	http://localhost:8000/
Django Version: 	1.10.6
Exception Type: 	ProgrammingError
Exception Value: 	

relation "docnow_user" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "docnow_user"
                                          ^

Exception Location: 	/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py in execute, line 64
Python Executable: 	/usr/local/bin/python3.6
Python Version: 	3.6.1
Python Path: 	

['/usr/local/bin',
 '/code',
 '/usr/local/lib/python36.zip',
 '/usr/local/lib/python3.6',
 '/usr/local/lib/python3.6/lib-dynload',
 '/usr/local/lib/python3.6/site-packages']

Server time: 	Fri, 24 Mar 2017 19:53:18 +0000
```

**Comment by edsu** [comment]
Yes, that's a temporary error that is being logged, but isn't fatal. I should make that clear in the message since it is causing confusion.

**Comment by edsu** [comment]
Oh my bad, that is an error you are seeing in your web browser?

**Comment by edsu** [comment]
I'm not sure how you deleted all the containers and images, but it looks like the database hasn't been completely set up.

Can you do this:

```
git pull
docker-compose down
docker-compose up
```

and see if it works any better?

**Comment by ryanfb** [comment]
Docker Compose doesn't have great built-in mechanisms for actually waiting for containers to completely start. The docs recommend using a wrapper like [`wait-for-it.sh`](https://github.com/vishnubob/wait-for-it) or [`dockerize`](https://github.com/jwilder/dockerize) to wait on a port opening up, or you could probably use the example `wait-for-postrgres.sh` script there: https://docs.docker.com/compose/startup-order/

**Comment by pbinkley** [comment]
Yeah, that was an error served to the browser. And I destroyed the images and containers with these steps: https://gist.github.com/JeffBelback/5687bb02f3618965ca8f . I've pulled (now on 66c346f), and it works! I'm able to create an account and get the email confirmation etc. Thanks for the fix!

**Comment by edsu** [comment]
oh great! thanks for testing and working the kinks out

**Comment by edsu** [comment]
@ryanfb thanks for the pointers to solving this timing issue better than sleeping for longer and longer periods of time -- reopening this so that it can be fixed.

**Comment by justinlittman** [comment]
@edsu For SFM, we use appdeps.py (https://github.com/gwu-libraries/appdeps). For example, https://github.com/gwu-libraries/sfm-ui/blob/master/Dockerfile#L43.

**Comment by edsu** [comment]
hey, thanks @justinlittman!
