### ISSUE TITLE
better-npm-run: not found

### ISSUE THREAD

**Issue by kayiwa** [DocNow/docnow#117]
with the most recent version build I'm running problems after 

```
docker-compose up
```
It builds the containers but fails on the node one with the following error. 

```
app_1            | npm info lifecycle docnow@~prestart:dev: docnow@
app_1            | npm info lifecycle docnow@~start:dev: docnow@
app_1            |
app_1            | > docnow@ start:dev /code
app_1            | > better-npm-run start:dev
app_1            |
app_1            | sh: 1: better-npm-run: not found
app_1            | npm info lifecycle docnow@~start:dev: Failed to exec start:dev script
app_1            | npm ERR! file sh
app_1            | npm ERR! code ELIFECYCLE
app_1            | npm ERR! errno ENOENT
app_1            | npm ERR! syscall spawn
app_1            | npm ERR! docnow@ start:dev: `better-npm-run start:dev`
app_1            | npm ERR! spawn ENOENT
app_1            | npm ERR!
app_1            | npm ERR! Failed at the docnow@ start:dev script.
app_1            | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
app_1            |
app_1            | npm ERR! A complete log of this run can be found in:
app_1            | npm ERR!     /root/.npm/_logs/2019-09-30T12_04_08_168Z-debug.log
```

**Comment by kayiwa** [comment]
The rabbit hole gets interesting. Updating to node 8.16.1 fixes the problem above. I work on macOS and css still doesn't load in the container. 
```
Error: Module build failed (from /code/node_modules/sass-loader/dist/cjs.js):
Error: Missing binding /code/node_modules/node-sass/vendor/linux_musl-x64-57/binding.node
Node Sass could not find a binding for your current environment: Linux/musl 64-bit with Node.js 8.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (/code/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/code/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:653:30)
    at Module._compile (/code/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (module.js:664:10)
    at Object.newLoader [as .js] (/code/node_modules/pirates/lib/index.js:104:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at getDefaultSassImpl (/code/node_modules/sass-loader/dist/index.js:198:10)
    at Object.loader (/code/node_modules/sass-loader/dist/index.js:80:29) main-33138f1c1c410183cc15.js:20893:7
```

Since our Dockerfile has this

https://github.com/DocNow/docnow/blob/c76441a09bf452785fb697b9f5c6b95a00163cde/Dockerfile#L4

it is expected.

**Comment by edsu** [comment]
I see the same in my docker environment. I think the bug might be related to this change, which I think expects a npm install to have happened outside the docker container?

https://github.com/DocNow/docnow/commit/cf0e89e342bbdb9896998ae6e4e0def38d633a40#diff-4e5e90c6228fd48698d074241c2ba760

I'll investigate further.

**Comment by edsu** [comment]
This was a change that @raffazizzi introduced to make it easier to test out new node dependencies without having to get inside the container. But requiring docker users to `npm install` prior to running `docker-compose up` really isn't feasible.

In the future node modules can be experimented with in development by doing a `docker-compose up` and then connecting to the running container with `docker exec -ti CONTAINER_ID bash`. Then you can `npm i modulename` and restart the container.
