### ISSUE TITLE
url-fetcher exiting and not restarting

### ISSUE THREAD

**Issue by edsu** [DocNow/docnow#173]
In testing (ansible deployment not docker-compose) I've noticed that the url-fetcher process can stop sometimes. I found this in `/var/log/syslog` which may explain why it is exiting?

```
syslog.1:Feb  4 19:07:53 smoketest npm[29902]: [winston] Attempt to write logs with no transports {"input":"http://Shiryn%20Ghermezian","code":"ERR_INVALID_URL","level":"warn","message":"ignoring invalid <link> href http://Shiryn%20Ghermezian Invalid URL: http://Shiryn%20Ghermezian","stack":"TypeError [ERR_INVALID_URL]: Invalid URL: http://Shiryn%20Ghermezian\n    at onParseError (internal/url.js:258:9)\n    at new URL (internal/url.js:334:5)\n    at extractHtmlMetadata (/var/local/docnow_app/docnow/node_modules/metaweb/metaweb.js:123:37)\n    at IncomingMessage.<anonymous> (/var/local/docnow_app/docnow/node_modules/metaweb/metaweb.js:53:26)\n    at IncomingMessage.emit (events.js:326:22)\n    at endReadableNT (_stream_readable.js:1241:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"}
```

**Comment by edsu** [comment]
It looks like this error might be because the logger isn't configure correctly to allow for messages from the underlying [metaweb](https://github.com/edsu/metaweb) library?
