### ISSUE TITLE
Warn about Callback URL being set incorrectly

### ISSUE THREAD

**Issue by kayiwa** [DocNow/docnow#32]
When one launches the app from AWS using our ansible repo you are met with this error when trying to set up the app

```
Error: Desktop applications only support the oauth_callback value 'oob'
    at Strategy.parseErrorResponse (/code/node_modules/passport-twitter/lib/strategy.js:206:12)
    at Strategy.OAuthStrategy._createOAuthError (/code/node_modules/passport-oauth1/lib/strategy.js:393:16)
    at /code/node_modules/passport-oauth1/lib/strategy.js:244:41
    at /code/node_modules/oauth/lib/oauth.js:543:17
    at passBackControl (/code/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/code/node_modules/oauth/lib/oauth.js:409:9)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

The steps to reproduce are

Clone https://github.com/DocNow/docnow-ansible

And run the playbook as described then enter the Twitter API key/secret.

That path in the error above isn't any "obvious" I can find.

**Comment by edsu** [comment]
I'm confused. The app that you brought up yesterday on our call worked fine.

**Comment by kayiwa** [comment]
We got to the "splash page" that allows you to enter Twitter API/KEY yesterday. So in that regard yes it worked. I'd never gone beyond this page in my tests before (sorry) and all attempts since have given me this error and I haven't the slightest clue where to start looking

**Comment by kayiwa** [comment]
I don't know if this is useful.

```
WARNING in ./src/client/components/AddPlace.js
app_1    |
app_1    | /code/src/client/components/AddPlace.js
app_1    |   30:7  warning  Unexpected alert  no-alert
app_1    |
app_1    | ✖ 1 problem (0 errors, 1 warning)
app_1    |
app_1    |  @ ./src/client/components/Trends.js 21:16-37
app_1    |  @ ./src/client/containers/TrendsPage.js
app_1    |  @ ./src/client/containers/App.js
app_1    |  @ ./src/client/index.js
app_1    |  @ multi ./index webpack-hot-middleware/client
app_1    | Child html-webpack-plugin for "index.html":
app_1    |          Asset    Size  Chunks  Chunk Names
app_1    |     index.html  567 kB       0
app_1    |     chunk    {0} index.html 541 kB [entry] [rendered]
app_1    |         [0] ./~/lodash/lodash.js 540 kB {0} [built]
app_1    |         [1] ./~/html-webpack-plugin/lib/loader.js!./src/client/index.html 529 bytes {0} [built]
app_1    |         [2] (webpack)/buildin/global.js 509 bytes {0} [built]
app_1    |         [3] (webpack)/buildin/module.js 517 bytes {0} [built]
app_1    | webpack: Compiled with warnings.
app_1    | ::ffff:128.112.65.39 - - [08/Aug/2017:15:12:45 +0000] "GET / HTTP/1.1" 200 216 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
app_1    | ::ffff:128.112.65.39 - - [08/Aug/2017:15:12:45 +0000] "GET /bundle.js HTTP/1.1" 200 3165002 "http://54.164.20.153:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
app_1    | ::ffff:128.112.65.39 - - [08/Aug/2017:15:12:50 +0000] "GET /api/v1/user HTTP/1.1" 401 27 "http://54.164.20.153:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
app_1    | ::ffff:128.112.65.39 - - [08/Aug/2017:15:12:50 +0000] "GET /api/v1/world HTTP/1.1" 200 2 "http://54.164.20.153:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
app_1    | ::ffff:128.112.65.39 - - [08/Aug/2017:15:12:50 +0000] "GET /api/v1/settings HTTP/1.1" 200 2 "http://54.164.20.153:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
app_1    | ::ffff:128.112.65.39 - - [08/Aug/2017:15:12:50 +0000] "GET /api/v1/setup HTTP/1.1" 200 5 "http://54.164.20.153:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
app_1    | node_redis: Deprecated: The HGETALL command contains a "null" argument.
app_1    | This is converted to a "null" string now and will return an error from v.3.0 on.
app_1    | Please handle this in your code to make sure everything works as you intended it to.
app_1    | (node:55) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'id' of null
app_1    | (node:55) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
app_1    | ::ffff:128.112.65.39 - - [08/Aug/2017:15:12:50 +0000] "GET /favicon.ico HTTP/1.1" 200 - "http://54.164.20.153:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
app_1    | ::ffff:128.112.65.39 - - [08/Aug/2017:15:12:50 +0000] "GET /api/v1/settings HTTP/1.1" 304 - "http://54.164.20.153:3000/settings/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
app_1    | ::ffff:128.112.65.39 - - [08/Aug/2017:15:12:50 +0000] "GET /favicon.ico HTTP/1.1" 200 - "http://54.164.20.153:3000/settings/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
app_1    | info: importing trends
app_1    | ::ffff:128.112.65.39 - - [08/Aug/2017:15:13:39 +0000] "PUT /api/v1/settings HTTP/1.1" 200 20 "http://54.164.20.153:3000/settings/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
app_1    | ::ffff:128.112.65.39 - - [08/Aug/2017:15:13:39 +0000] "GET /auth/twitter/ HTTP/1.1" 500 1094 "http://54.164.20.153:3000/settings/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
app_1    | Error: Desktop applications only support the oauth_callback value 'oob'
app_1    |     at Strategy.parseErrorResponse (/code/node_modules/passport-twitter/lib/strategy.js:206:12)
app_1    |     at Strategy.OAuthStrategy._createOAuthError (/code/node_modules/passport-oauth1/lib/strategy.js:393:16)
app_1    |     at /code/node_modules/passport-oauth1/lib/strategy.js:244:41
app_1    |     at /code/node_modules/oauth/lib/oauth.js:543:17
app_1    |     at passBackControl (/code/node_modules/oauth/lib/oauth.js:397:13)
app_1    |     at IncomingMessage.<anonymous> (/code/node_modules/oauth/lib/oauth.js:409:9)
app_1    |     at emitNone (events.js:110:20)
app_1    |     at IncomingMessage.emit (events.js:207:7)
app_1    |     at endReadableNT (_stream_readable.js:1045:12)
app_1    |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
app_1    |     at process._tickCallback (internal/process/next_tick.js:180:9)
app_1    | ::ffff:128.112.65.39 - - [08/Aug/2017:15:13:39 +0000] "GET /__webpack_hmr HTTP/1.1" 200 - "http://54.164.20.153:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
app_1    | ::ffff:128.112.65.39 - - [08/Aug/2017:15:13:39 +0000] "GET /api/v1/trends HTTP/1.1" - - "http://54.164.20.153:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
app_1    | ::ffff:128.112.65.39 - - [08/Aug/2017:15:13:39 +0000] "GET /favicon.ico HTTP/1.1" 200 - "http://54.164.20.153:3000/auth/twitter/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
```

**Comment by edsu** [comment]
It looks like it's the result of Callback URL not being defined for the app over at https://apps.twitter.com. Ideally docnow would tell the user to go put a URL in there rather than throwing this obscure error.

**Comment by alexandradm** [comment]
this URL works for local env: http://localhost:3000/auth/twitter/callback

**Comment by edsu** [comment]
The app now warns about this issue and incorrect keys. 4 years late is better than never?
