### ISSUE TITLE
Intermittent errors from getTrendsAtPlace.

### ISSUE THREAD

**Issue by edsu** [DocNow/docnow#42]
The twitter.getTrendsAtPlace() function occasionally throws this error, I think it's happening when the quota for requesting trends has been exceeded. The function should check for this error and back off.

```
Unhandled rejection TypeError: Cannot read property 'locations' of undefined
    at /Users/ed/Projects/docnow/src/server/twitter.js:50:19
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at /Users/ed/Projects/docnow/src/server/twitter.js:48:12
    at Promise (<anonymous>)
    at Twitter.getTrendsAtPlace (/Users/ed/Projects/docnow/src/server/twitter.js:45:12)
    at Array.map (<anonymous>)
    at /Users/ed/Projects/docnow/src/server/db.js:170:43
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Unhandled rejection TypeError: Cannot read property 'locations' of undefined
    at /Users/ed/Projects/docnow/src/server/twitter.js:50:19
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at /Users/ed/Projects/docnow/src/server/twitter.js:48:12
    at Promise (<anonymous>)
    at Twitter.getTrendsAtPlace (/Users/ed/Projects/docnow/src/server/twitter.js:45:12)
    at Array.map (<anonymous>)
    at /Users/ed/Projects/docnow/src/server/db.js:170:43
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Unhandled rejection TypeError: Cannot read property 'locations' of undefined
    at /Users/ed/Projects/docnow/src/server/twitter.js:50:19
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at /Users/ed/Projects/docnow/src/server/twitter.js:48:12
    at Promise (<anonymous>)
    at Twitter.getTrendsAtPlace (/Users/ed/Projects/docnow/src/server/twitter.js:45:12)
    at Array.map (<anonymous>)
    at /Users/ed/Projects/docnow/src/server/db.js:170:43
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by edsu** [comment]
I'm not seeing these errors any more, or at least the numbers and callbacks will have changed a lot since it was opened. We can reopen if it still pops up in the logs.
