### ISSUE TITLE
Error after entering consumer key and secret

### ISSUE THREAD

**Issue by silverjim12** [DocNow/docnow#97]
Hello,
I get the following error after entering consumer key and secret and press save:
Error: Unknown authentication strategy "twitter"
    at attempt (/code/node_modules/passport/lib/middleware/authenticate.js:173:37)
    at authenticate (/code/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)
    at next (/code/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/code/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)
    at /code/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/code/node_modules/express/lib/router/index.js:335:12)
    at next (/code/node_modules/express/lib/router/index.js:275:10)
    at SessionStrategy.strategy.pass (/code/node_modules/passport/lib/middleware/authenticate.js:325:9)
    at SessionStrategy.authenticate (/code/node_modules/passport/lib/strategies/session.js:71:10)
    at attempt (/code/node_modules/passport/lib/middleware/authenticate.js:348:16)
    at authenticate (/code/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/code/node_modules/express/lib/router/index.js:317:13)
    at /code/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/code/node_modules/express/lib/router/index.js:335:12)
    at next (/code/node_modules/express/lib/router/index.js:275:10)
    at initialize (/code/node_modules/passport/lib/middleware/initialize.js:53:5)
    at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/code/node_modules/express/lib/router/index.js:317:13)
    at /code/node_modules/express/lib/router/index.js:284:7

Could you please help me out?

**Comment by edsu** [comment]
Hi @silverjim12 -- thanks for entering this as an issue ticket. In your Twitter App can you set the `Callback URL` to something like:

     https://example.com/auth/twitter/callback 

Where `example.com` is changed to your instance hostname? It can be 127.0.0.1 if you are running locally.

Also be sure that the `Sign in With Twitter` checkbox is checked. We should really have an error message that conveys this instead of the very unhelpful error that you got.

**Comment by jeremyboggs** [comment]
I'm getting an error as well that says my callback URL isn't approved:

```
Error: Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings
    at Strategy.parseErrorResponse (/code/node_modules/passport-twitter/lib/strategy.js:206:12)
    at Strategy.OAuthStrategy._createOAuthError (/code/node_modules/passport-oauth1/lib/strategy.js:393:16)
    at /code/node_modules/passport-oauth1/lib/strategy.js:244:41
    at /code/node_modules/oauth/lib/oauth.js:543:17
    at passBackControl (/code/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/code/node_modules/oauth/lib/oauth.js:409:9)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```
I've used https://127.0.0.1/auth/twitter/callback on my app's settings. Should this work instantly when I update my app's settings, or do I need to wait a bit?

I also don't see a "sign in with Twitter" checkbox on my form. (Using latest Chrome.)

**Comment by edsu** [comment]
@jeremyboggs are you in the new developer.twitter.com area or the old apps.twitter.com area? I don't know if Twitter could make this more confusing, but I wouldn't want to dare them :-)

**Comment by jeremyboggs** [comment]
Nevermind! I also tried to use localhost:3000, but apparently I forgot how to spell 'localhost'.

**Comment by jeremyboggs** [comment]
> are you in the new developer.twitter.com area or the old apps.twitter.com area? I don't know if Twitter could make this more confusing, but I wouldn't want to dare them :-)

I was in the apps.twitter.com. (I'm still waiting for approval for an app through developer.twitter.com.) Using `localhost:3000/auth/twitter/callback` works fine.

**Comment by edsu** [comment]
Oh great! I'm glad you were able to figure it out.

**Comment by edsu** [comment]
The implementation around this has changed substantially. If you get a chance to give it a try please let us know if you continue to have trouble.
