### ISSUE TITLE
app fails to launch (node fails)

### ISSUE THREAD

**Issue by kayiwa** [DocNow/docnow#98]
when running docker-compose up the node fails to run.

**Comment by edsu** [comment]
If there's an obvious error message related to this failure it would be useful to cut and paste in here.

**Comment by edsu** [comment]
Hmm, maybe this?

```
/Users/ed/Projects/docnow/src/commands/server.js:123
  var urlFetcher = new UrlFetcher();
                   ^

ReferenceError: UrlFetcher is not defined
    at Object.<anonymous> (/Users/ed/Projects/docnow/src/commands/server.js:75:3)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at loader (/Users/ed/Projects/docnow/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ed/Projects/docnow/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at Object.<anonymous> (/Users/ed/Projects/docnow/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by kayiwa** [comment]
Ways to replicate.
```
docnow master % docker-compose version
docker-compose version 1.23.2, build unknown
docker-py version: 3.6.0
CPython version: 3.7.2
OpenSSL version: OpenSSL 1.0.2q  20 Nov 2018
docnow master % git log
commit ef5cec8325ef51c46b9c7b670b337c683d533243 (HEAD -> master, origin/master, origin/HEAD)
Author: Ed Summers <ehs@pobox.com>
Date:   Sat Jan 19 07:32:33 2019 -0500

    trying new keys to see if travis works
```
Will post the logs once it launches

**Comment by kayiwa** [comment]
looks like you got it.

**Comment by kayiwa** [comment]
this commit https://github.com/DocNow/docnow/commit/058937bf550f62b2eea20d53e141933801d7d982 fixes it for me.

**Comment by edsu** [comment]
Me too!
